### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [9]:
import numpy as np

n = int(input('Введите число N: '))
a_list = [i for i in range(0,n)]
a_list.reverse()

arr = np.array(a_list)
mat = np.diag(arr)
print(mat)
print(sum(mat.diagonal()))

# 2 вариант 
# mat_2 = np.diag(np.arange(n-1, -1, -1), k=0)
# print(mat_2)
# print(sum(mat_2.diagonal()))

Введите число N: 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45
